### PR TITLE
Additional round-trip unit testing for numeric types, and some fixes to match.

### PR DESCRIPTION
**Pull request by BBI-YggyKing**
Added new JsonRoundTripTest.cs, which converts numbers to json, then back again, then checks to see that we got what we started with. Do this for 8/16/32/64-bit signed and unsigned integers and float/double/decimal. Test 0, 1, Min, Max, and (for reals) epsilon.

This uncovered some issues with too-big numbers not getting handled correctly (ulong and decimal-formatted-as-integer), which have mostly been addressed.

Still need to see if comparison methods can be removed in favour of a strict equality test and true loss-less round-tripping. In principle this is what decimal is for, so it's a pity it's not currently supported correctly (we always go through a double to parse a decimal, which introduces loss of precision).

A better approach would probably be to get rid of JsonReader.ProcessNumber, and only do the string parsing when the target type is known.

Also note new Visual Studio solution and project files, located in the build folder (where they belong ;-). Also note that I'm not presently compiling the Unity files -- these ought to be in a separate folder and assembly.

Any questions fire away -- you can either merge this request or we can just talk about it for a bit.

cheers,
yggy

### CODE REVIEW

**Comment by BBI-YggyKing** [comment]
Sounds like you and I have different approaches to how we build our Unity projects, so there's some discussion to be had there. We've shifted to putting almost everything in DLL's (and building them with Visual Studio). Compiler directive is an option though.

I just started using Unity Test Tools recently, it's a good package. I can look at how to get the LitJson tests working with them, it should be straightforward. The way I have things set up here, I press F5 in Visual Studio and it launches NUnit GUI to run through the tests, which I can do in the Visual Studio debugger. At present you need to define the NUnitBin environment variable to point to an (external) install of NUnit -- agreed that this isn't ideal if we want to keep things self-contained, but it was a quick way for me to get up and running.

**Comment by Mervill** [comment]
Oh that's neat! Do you get a speed increase from that or is it an organisational thing? Do you use UnityVS?

Adding the compiler directive `STATIC_DLL` seems like the appropriate fix.

``` C#
#if STATIC_DLL
    if (instType.IsClass || underlyingType != null) {
#else
    /* IsClass is made a property here as a comparability
    patch for WinRT build targets, see UnityPlatform.cs */
    if (instType.IsClass() || underlyingType != null) {
#endif
```

You can then exclude UnityPlatform.cs and UnityTypeBindings.cs from the VS project.

I'm coming at this project assuming the uncompiled source will be imported to the Unity project, so feel free to set up the VS project files however you want.

**Comment by BBI-YggyKing** [comment]
The DLL thing is mostly organizational, we have multiple projects and it's a nice to way to manage dependencies -- in particular we have a stack of code that doesn't depend on Unity in any way. It's a speed boost in the editor, since Unity doesn't need to recompile everything all the time. And in theory it could be faster at runtime, as I would expect Visual Studio to have better optimizations than Mono, but we haven't measured it to know if that's the case.

One of our programmers tried UnityVS -- it's cool, but falls over with some of the stuff we're doing in our game and we didn't dig too much deeper. Also most of us are using Visual Studio Express, which doesn't support plugins like UnityVS.

Visual Studio also makes it easy to configure multiple platforms, each with different #defines, which would be one way to set up for multi-platform support. It's too bad Unity doesn't provide an easy mechanism for including platform-specific assets (in this case DLL's). For us we manage a stack of DLL's already, so one more would be no big deal. Your method has the advantage of rebuilding automatically under Unity's control, which keeps things simple for anyone not using DLL's.

The way we use DLL's and the way we're currently using LitJson had me thinking about the build process and the package in a certain way, for better or worse. I'm confident there's a way to get the best of both worlds -- should be simple enough to allow people to use either DLL's or loose scripts, as they prefer.

More philosophically, I think LitJson should remain Unity-independent, with a thin glue layer to make it easier to use in Unity. This shouldn't be a big deal either -- something as simple as separate source/LitJson and source/Unity folders would probably keep me happy. ;-)

**Comment by Mervill** [comment]
Alright, rearrange the files and push a new commit to this branch, it'll be automatically added to the pull request.

**Comment by BBI-YggyKing** [comment]
Sounds good, I'll get to it today or tomorrow.

**Comment by BBI-YggyKing** [comment]
So much for "today or tomorrow" :-p

I've been in touch with the original developer of LitJson, sounds like he's not leaving it orphaned after all, so I'm inclined to modify as little as possible, including keeping file and folder layout and coding style as-is, to facilitate future merges.

**Comment by Mervill** [comment]
I've merged this request with the repository, I also committed the changes we discussed to make the library buildable to both Unity3D and as a generic DLL.

**Comment by BBI-YggyKing** [comment]
Excellent :)

**Pull request merged**
